### ISSUE TITLE
Add web interface

### ISSUE THREAD

**Issue by RaasAhsan** [PacketFire/apophis#18]
`Quart`

**Comment by RaasAhsan** [comment]
Since Flask doesn't run `asyncio`, another solution is to run a separate Python service running Flask and send messages to the bot via postgres listen/notify framework.

This is beneficial for several reasons:
- The bot and the web service need not be on the same process, container or even machine.
- The web service can be released, deployed and scaled independently from the bot.

**Comment by bramz** [comment]
For asynchronicity we've decided to use [aiohttp](https://github.com/aio-libs/aiohttp).
