### ISSUE TITLE
Use Discord user ID instead of username

### ISSUE THREAD

**Issue by RaasAhsan** [PacketFire/apophis#36]
In both the `songs` and `permissions` tables, we are  identifying a Discord user via their username. This can potentially fail in distinguishing two users: it is entirely possible that two Discord users share the same username (remember not pacifico?). It is also insufficient to use both the username and the user number, both these values can be changed at the discretion of a user. 

The only field that distinguishes any two users is their Discord user ID, which is accessible in `discord.py` via `message.author.id`. It looks something like `327973168934463462`. It is a very large number, but its also safe for us to save this as a string in postgres.

We should use the Discord user ID instead of the username/number to identify users.

**Comment by sabinprj** [comment]
I think it's done now so we can close this issue.
